### ISSUE TITLE
Compile fails when using struct properties as format string

### ISSUE THREAD

**Issue by asonix** [Plume-org/gettext-macros#1]
In order for the proc macro to recognize the argument properly, I need to put parentheses around struct properties.

```rust
i18n!(catalog, (my_struct.my_property))
```

This causes a lot of compile warnings, since Rust thinks the parentheses are unneeded. If I remove the parentheses, I get compile errors, since the macro stops reading at the `.`

![image](https://user-images.githubusercontent.com/5304643/51444711-ca02f200-1cc0-11e9-8c6c-a02d1c20ca50.png)

**Comment by elegaanz** [comment]
As I explained you on Matrix, it is because a str literal is required, otherwise we can't write it to the `.pot` file.

However we could allow any expression here, and make another macro that could be used anywhere and just mark a string as translatable, without actually translating it, so you could do:

```rust
let alert = Alert {
    message: translatable!("foo bar") // just adds the message to the .pot, without translating it
};
i18n!(catalog, alert.message); // translate it now
```

**Comment by asonix** [comment]
Just letting you know, I've worked everything out to not need to do this anymore. I do think that there should be some docs talking about why this is, and maybe figure out how to make things that aren't string literals be compile errors

**Comment by elegaanz** [comment]
FYI, you can now (with the latest commit on `main`, I didn't released it yet) mark a string as translatable without needing a `gettext::Catalog`, with `t!`:

```rust
// Doesn't translate anything, just adds the string to the .pot file
let message = t!("Hello!");

// Later, when you have a Catalog, translate the string for real
i18n!(catalog, message);
```
