### ISSUE TITLE
version 0.6?

### ISSUE THREAD

**Issue by Valodim** [Plume-org/gettext-macros#15]
Hey there! Thanks for developing this crate, it is well appreciated since we use it for [Hagrid](https://gitlab.com/hagrid-keyserver/hagrid/).

I noticed there is a [version 0.6 on crates.io](https://crates.io/crates/gettext-macros/0.6.0), but this repository contains only version 0.5.2?

**Comment by elegaanz** [comment]
A more up-to-date version can be found here: https://git.joinplu.me/plume/gettext-macros/

The gitea is a bit buggy though, it won't let me open any file, and I cannot check in the Cargo.toml if it is the 0.6.0 version, or if the commits are… somewhere else. But I think that's where the last commits are.

**Comment by Valodim** [comment]
"template: repo/header:95:151: executing "repo/header" at <EscapePound>: invalid value; expected string" a bit buggy indeed :)

would you mind pushing those commits to this repo? alternatively, if the gitea works again, I would recommend pointing the crates.io repository link to it, and leaving a pointer in the readme here that the official location has moved.

thanks for getting back to me, in any case

**Comment by trinity-1686a** [comment]
> The gitea is a bit buggy though, it won't let me open any file, and I cannot check in the Cargo.toml if it is the 0.6.0 version, or if the commits are… somewhere else. But I think that's where the last commits are.

Default branch was master, but we moved to using main instead, so it did not find the branch. I changed default branch and it's now fixed.
It's also in 0.5.2, no traces of 0.6.
Things are well configured so that Github is an up to date mirror of gitea

**Comment by elegaanz** [comment]
I lost a lot of files recently and I don't think I have the last commits on my computer. And I won't have access to the hard drive where I made a potential backup until a few weeks or more… I'll see if it is possible to get the code and the git history from what is saved on crates.io.

>  Things are well configured so that Github is an up to date mirror of gitea

It looks like the latest commit on gitea is 38f16d7418 while it is 843d068a38 on here… there must have been an issue when syncing

**Comment by elegaanz** [comment]
So, I downloaded the 0.6.0 archive from crates.io and appart from the version number it is the same as the last commit on Gitea. I will update the version number and push to gitea (hopefully it will mirror to github this time, otherwise I will push manually).

**Comment by Valodim** [comment]
Yup, it is. If it's useful for you, I recovered the changes in a commit [here](https://github.com/Valodim/gettext-macros/commit/cc0deb4619901317f61dfaabae591a5199aad51a) :)

\\\\ edit

ah, I got sniped! nvm ;)

**Comment by elegaanz** [comment]
Normally the code on crates.io, gitea and github is the same now. I think we can close this.
