### ISSUE TITLE
regression with quotation marks " in 0.6

### ISSUE THREAD

**Issue by Valodim** [Plume-org/gettext-macros#16]
when I update to gettext-macros to 0.6, I'm receiving this error from gettext during compilation:

```
.../hagrid/po/hagrid/hagrid.pot:35: keyword "email" unknown
```

-> line 35 of hagrid.pot:

```
msgid "We found an entry for <span class="email">{{ query }}</span>:"
```

It seems that gettext-macros doesn't escape quotation marks in its `.pot` output anymore?

~~Relatedly (#15), I couldn't look into this issue myself since there's no source for it :)~~

**Comment by KitaitiMakoto** [comment]
Fixed via #17
