### ISSUE TITLE
Obscure error message when msgmerge is not available

### ISSUE THREAD

**Issue by khimaros** [Plume-org/gettext-macros#7]
I encountered this when building Plume:

```
$ cargo web deploy -p plume-front
[...]
   Compiling plume-front v0.1.0 (MASKED/plume-front)
error: proc macro panicked
  --> plume-front/src/main.rs:18:1
   |
18 | compile_i18n!();
   | ^^^^^^^^^^^^^^^^
   |
   = help: message: Couldn't update PO file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
error: aborting due to previous error
error: Could not compile `plume-front`.
```

The "No such file or directory" is referring to msgmerge. It would be helpful to include the missing path as part of the error message, or even explicitly warn about gettext unavailability.

**Comment by khimaros** [comment]
Was this fixed by a particular merge or closing for another reason?

**Comment by trinity-1686a** [comment]
It's probably somewhere in [this commit](https://github.com/Plume-org/gettext-macros/commit/3325c6b16718230990117b7523ad6c6b99e03e1b), ~~although I can't tell which change it's exactly.~~

Edit : the specific line that failed for you is [this one](
https://github.com/Plume-org/gettext-macros/commit/3325c6b16718230990117b7523ad6c6b99e03e1b#diff-b4aea3e418ccdb71239b96952d9cddb6R315)
